@startuml CFA-C

class DataType {
    +string type
    +int size
}

class FragmentDimension {
    +string name
    +int length
}

class Fragment {
    +int [] location
    -int [] index
    +string file
    +string format
    +string address
    +string units
}

class AggregationInstructions {
    +string location
    -bool location_scaler
    +string file
    +string format
    -bool format_scaler
    +string address
}

class AggregatedData {
    +string units
}

class AggregatedDimension {
    +string name
    +int length
}

class AggregationVariable {
    +string name
}

class AggregationContainer {
    +string path
    +string name
    -string format
    -string external_id
    -bool serialised
}

AggregationVariable "1" o--> "0..*" AggregatedDimension
AggregationVariable "1" *--> "1" AggregatedData
AggregatedData "1" *--> "0..*" Fragment
Fragment "1" *--> "0..*" FragmentDimension
AggregationVariable "1" o--o "1..*" FragmentDimension
AggregatedDimension "1" *-> "1" DataType
AggregationVariable "1" *--> "1" AggregationInstructions
AggregationVariable "1" *-> "1" DataType
Fragment "1" *-> "1" DataType
AggregationContainer "1" *--> "0..*" AggregationVariable
AggregationContainer "1" *--> "0..*" AggregatedDimension
AggregationContainer "1" *--> "0..*" AggregationContainer
@enduml
