@startuml cfa_class_diagram
left to right direction
class DataType #lightgrey {
    +int type
    +int size
}

class FragmentDimension #cyan {
    +string name
    +int length
}

class Fragment #cyan {
    +int [] location
    -int [] index
}

class FragmentDatum #cyan {
    +string term
    +void* value
    +int size
}

class AggregationInstruction #coral {
    +string term
    +string value
    +bool scalar
}

class AggregatedData #coral {
    +string units
}

class AggregatedDimension #hotpink {
    +string name
    +int length
}

class AggregationVariable #coral{
    +string name
}

class AggregationContainer #lightskyblue {
    +string path
    +string name
    -string format
    -string external_id
    -bool serialised
}

AggregationVariable "1" o--> "0..*" AggregatedDimension
AggregationVariable "1" *--> "1" AggregatedData
AggregatedData "1" *--> "0..*" Fragment
Fragment "1" *--> "0..*" FragmentDimension
Fragment "1" *--> "0..*" FragmentDatum
AggregationVariable "1" o--o "1..*" FragmentDimension
AggregatedDimension "1" *-> "1" DataType
AggregationVariable "1" *--> "1..*" AggregationInstruction
AggregationVariable "1" *-> "1" DataType
AggregationInstruction "1" *-> "1" DataType
FragmentDatum "1" *-> "1" DataType
AggregationContainer "1" *--> "0..*" AggregationVariable
AggregationContainer "1" *--> "0..*" AggregatedDimension
AggregationContainer "1" *--> "0..*" AggregationContainer
@enduml
