@startuml cfa_class_diagram

class DataType #lightgrey {
    +string type
    +int size
}

class FragmentDimension #cyan {
    +string name
    +int length
}

class Fragment #cyan {
    +int [] location
    -int [] index
    +string file
    +string format
    +string address
    +string units
}

class AggregationInstructions #coral {
    +string location
    -bool location_scalar
    +string file
    +string format
    -bool format_scalar
    +string address
}

class AggregatedData #coral {
    +string units
}

class AggregatedDimension #hotpink {
    +string name
    +int length
}

class AggregationVariable #coral{
    +string name
}

class AggregationContainer #lightskyblue {
    +string path
    +string name
    -string format
    -string external_id
    -bool serialised
}

AggregationVariable "1" o--> "0..*" AggregatedDimension
AggregationVariable "1" *--> "1" AggregatedData
AggregatedData "1" *--> "0..*" Fragment
Fragment "1" *--> "0..*" FragmentDimension
AggregationVariable "1" o--o "1..*" FragmentDimension
AggregatedDimension "1" *-> "1" DataType
AggregationVariable "1" *--> "1" AggregationInstructions
AggregationVariable "1" *-> "1" DataType
Fragment "1" *-> "1" DataType
AggregationContainer "1" *--> "0..*" AggregationVariable
AggregationContainer "1" *--> "0..*" AggregatedDimension
AggregationContainer "1" *--> "0..*" AggregationContainer
@enduml
